services:
  client:
    container_name: portfolio_client
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    networks:
      - portfolio_network
    ports:
      - "3002:3000"

  strapi:
    container_name: portfolio_strapi_cms
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    env_file: apps/cms/.env
    volumes:
      - ./apps/cms/public/uploads:/app/apps/cms/public/uploads
    networks:
      - portfolio_network
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: portfolio_strapi_db
    restart: unless-stopped
    env_file: apps/cms/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network:
    driver: bridge