services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_strapi_db
    restart: unless-stopped
    env_file: apps/cms/.env.local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network:
    driver: bridge