import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { LayoutContextProvider } from '@/context/layout-context'
import { Navbar } from '@/components/header/navbar'
import { Footer } from '@/components/footer/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <LayoutContextProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-white font-inter overflow-x-hidden`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </LayoutContextProvider>
    </html>
  )
}
